[package]
name = "rust-web-server"
version = "0.1.0"
edition = "2018"

[dependencies]
async-graphql = "7.0.3"
async-graphql-axum = "7.0.3"
axum = "0.7.5"
serde = "1.0.200"
tokio = { version = "1.37.0", features = ["full"] }
